project_name: vendel

builds:
  - main: .
    binary: vendel
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - pb_public/**/*

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  github:
    owner: JimScope
    name: vendel
